name: Update

on:
  schedule:
    - cron: '0 * * * 1'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      id: date
      run: echo "date=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV

    - name: Update
      run: |
        # 清环境
        rm -f *.m3u *.txt EPG.xml README.md

        # 央视源
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CCTV.m3u
        sed -i -n '/央视频道/,+1p' CCTV.m3u
        sed -i '1i #EXTM3U' CCTV.m3u
        sed -i '/^\s*$/d' CCTV.m3u

        # 卫视源
        touch CNTV.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV1.m3u && sed -i -n '/卫视频道/,+1p' CNTV1.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV2.m3u && sed -i -n '/NewTV系列/,+1p' CNTV2.m3u
        wget https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O CNTV3.m3u && sed -i -n '/超清频道/,+1p' CNTV3.m3u
        cat CNTV1.m3u >> CNTV.m3u
        cat CNTV2.m3u >> CNTV.m3u
        cat CNTV3.m3u >> CNTV.m3u
        rm -f CNTV1.m3u CNTV2.m3u CNTV3.m3u
        sed -i '1i #EXTM3U' CNTV.m3u
        sed -i '/^\s*$/d' CNTV.m3u

        # 4K源
        wget https://raw.githubusercontent.com/YanG-1989/m3u/main/Gather.m3u -O 4k.m3u
        wget https://raw.githubusercontent.com/YanG-1989/m3u/main/Gather.m3u -O 4k.txt
        sed -i -n '/4K/,+1p' 4k.m3u
        sed -i -n '/4k/,+1p' 4k.txt
        echo '' >> 4k.m3u && cat 4k.txt >> 4k.m3u
        rm -f 4k.txt
        sed -i '1i #EXTM3U' 4k.m3u
        sed -i '/^\s*$/d' 4k.m3u

        # 整合源（无成人）
        touch IPTV.m3u
        cat CCTV.m3u >> IPTV.m3u
        cat CNTV.m3u >> IPTV.m3u
        sed -i '/#EXTM3U/d' IPTV.m3u
        sed -i '1i #EXTM3U' IPTV.m3u
        sed -i '/^\s*$/d' IPTV.m3u

        # 整合源
        touch IPTV-all.m3u
        cat CCTV.m3u >> IPTV-all.m3u
        cat CNTV.m3u >> IPTV-all.m3u
        # Uncomment following lines if you want to include Adult sources
        # cat Adult.m3u >> IPTV-all.m3u
        sed -i '/#EXTM3U/d' IPTV-all.m3u
        sed -i '1i #EXTM3U' IPTV-all.m3u
        sed -i '/^\s*$/d' IPTV-all.m3u
        
        # 节目源
        wget https://epg.112114.xyz/pp.xml -O EPG.xml
        # readme.md
        echo "Auto Update IPTV in ${{ env.date }} " > README.md

    - name: Clean
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "${{ env.date }}"
        git branch -D main
        git branch -m main
        git push --set-upstream origin main --force
